# Generated by Django 3.2 on 2022-04-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='in_stock',
        ),
    ]
