# Generated by Django 3.2 on 2022-08-30 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0008_auto_20220830_1911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('meal_name', 'user')},
        ),
    ]
