# Generated by Django 3.2 on 2022-08-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_alter_meal_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set(),
        ),
    ]
