# Generated by Django 3.2 on 2022-08-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_alter_meal_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
    ]
