# Generated by Django 3.2 on 2022-08-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_auto_20220830_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='planned',
        ),
    ]
